### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by ondras** [ondras/wwwsqldesigner#118]
_From [sarafan...@gmail.com](https://code.google.com/u/103080847713167595440/) on October 18, 2010 19:22:29_

What steps will reproduce the problem? 1. How can I use back-end for MSSQL, I don't see any configuration back-end file for it?

I am using the latest version.

_Original issue: http://code.google.com/p/wwwsqldesigner/issues/detail?id=111_

**Comment by ondras** [comment]
_From [ondrej.zara](https://code.google.com/u/ondrej.zara/) on October 18, 2010 23:02:26_

There is no MSSQL backend at the moment. Additionaly, I have no access to MS SQL server, so someone (you, for instance?) must contribute this code.

**Comment by ondras** [comment]
_From [dcarnelu...@enpartes.com](https://code.google.com/u/106238035320906271102/) on August 05, 2011 05:27:39_

how can i add back end support for mssql? how can i contribute with that?

**Comment by ondras** [comment]
_From [ondrej.zara](https://code.google.com/u/ondrej.zara/) on August 05, 2011 13:30:42_

Reading https://code.google.com/p/wwwsqldesigner/wiki/Extending might be a good starting point; studying other backends ( https://code.google.com/p/wwwsqldesigner/source/browse/backend ) can help too.

**Comment by ondras** [comment]
MSSQL already added.

**Comment by eduardoquirozcl** [comment]
I change my DB model from mysql to MSSQL, but generated code and XML is still in mysql. How can i get the MS SQL DB code?

**Comment by ondras** [comment]
Dupe with #219.
