### ISSUE TITLE
Request: shareable URLS that load a saved XML

### ISSUE THREAD

**Issue by tchoulihan** [ondras/wwwsqldesigner#195]
This is a feature request.

Since the demo at http://ondras.zarovi.cz/sql/demo/ already has the ability to save and load files, wouldn't it be really cool if you could just have a link that loads up a saved file?

Something like 
`http://ondras.zarovi.cz/sql/demo?load_xml=yada_yada`

This would really help me collaborate with others on schemas.

**Comment by ondras** [comment]
Already works: http://ondras.zarovi.cz/sql/demo/?keyword=default

I will adjust this project's webpage link accordingly.

**Comment by tchoulihan** [comment]
oops, my bad. Thanks a ton good sir!

**Comment by tchoulihan** [comment]
Just a reminder, it would be a good idea to add this to the documentation page. I couldn't find it, so I had to find this issue again.

**Comment by ondras** [comment]
Already present -- the last-but-one paragraph at https://github.com/ondras/wwwsqldesigner/wiki/Manual. I am not sure how to make this one particularly visible to newcomers.

**Comment by tchoulihan** [comment]
Ah I see, it wasn't obvious to me to find that. Its up to your discretion, but in my view, when I click documentation, it would probably be most helpful to link to this: https://github.com/ondras/wwwsqldesigner/wiki/Manual#basics

The best github front pages are ones that also tell you how to use it, like this one: https://github.com/antirez/redis
