### ISSUE TITLE
Add XML load / save via Dropbox

### ISSUE THREAD

**Issue by tempelmann** [ondras/wwwsqldesigner#197]
It would be great if we could load the XML data from and save to Dropbox and similar "cloud storage" providers.

Dropbox API described here: https://www.dropbox.com/developers/dropins

**Comment by tempelmann** [comment]
Oh, darn. That Dropbox API I pointed out won't work here because it only can load/save actual files on the client's file system. To load/save the xml as a string, the Core API needs to be used, which is more work.

**Comment by tempelmann** [comment]
I just spent the last few hours learning a little bit of Javascript coding to get this working. See the new pull request. If you merge it, feel free to close this.

**Comment by ondras** [comment]
Very cool. I will merge the PR, but let's keep this issue open to coordinate adding support for multiple similar storage providers.

**Comment by ondras** [comment]
Some basic work in https://github.com/ondras/wwwsqldesigner/tree/storage ...

**Comment by tempelmann** [comment]
This can be closed, can't it? I'll do it now. Undo if you think there's still something missing about this.

**Comment by ondras** [comment]
> This can be closed, can't it?

Hmm, probably. The `storage` branch is not merged yet, but it needs no further tracking.
