### ISSUE TITLE
Load/Save redesign: shows wrong button set initially

### ISSUE THREAD

**Issue by tempelmann** [ondras/wwwsqldesigner#204]
See screenshot:

![screen shot 2015-06-16 at 10 23 07](https://cloud.githubusercontent.com/assets/461920/8178820/056205d6-1412-11e5-85ee-328922d9d96d.PNG)

At start, the top popup says "browser storage" but the buttons below it show those for the server storage. This happens every time to me when I reload the page.

**Comment by ondras** [comment]
Interesting, @tempelmann. Browser/OS, please?

**Comment by ondras** [comment]
Ah, I can reproduce in Chrome (Linux).

**Comment by ondras** [comment]
Shall be fixed now.
