### ISSUE TITLE
[RELATION] Colors undefined

### ISSUE THREAD

**Issue by nicovak** [ondras/wwwsqldesigner#206]
Hello and thank you for you'r great tool.

I just hosted this repo on my personal server.
I have an issue with the relations's colors. The stroke attribute is set to undefined. I tested it with firefox and chrome, with an imported XML and a new one.
The stroke path must be a CSS color. The file is : js/relation.js

SVG > PATH > stroke attr

Thanks

**Comment by ondras** [comment]
Yeah, this is already fixed in the new "storage" branch. Let me backport this fix to the master as well.

**Comment by ondras** [comment]
Fixed; please confirm that it works now.

**Comment by nicovak** [comment]
It works ! Thank you :)
