### ISSUE TITLE
Sql Import

### ISSUE THREAD

**Issue by josdea** [ondras/wwwsqldesigner#211]
Perhaps I'm mistaken, but previous it was possible to import sql script into the import screen and it generated the tables as they were.   For example I use sqldesigner to create a number of tables and then I generate the sql scripts, I then refresh or return another day with sql code and try to import that code to recreate the tables.   I thought this used to work..

Thanks

**Comment by ondras** [comment]
No, this never worked.

There are only two ways of **loading** data into the app:

  1. by loading a previously saved XML,

  2. by using the `import` command on your database backend. Not all backends implement this functionality.

Loading SQL was never supported (and is a complex and hard task, see https://github.com/ondras/wwwsqldesigner/issues/194).
