### ISSUE TITLE
No links lines between tables show up outside the standard are when loading...

### ISSUE THREAD

**Issue by klmedia** [ondras/wwwsqldesigner#216]
The link lines are not visible outside the standard drawing area when loading a saved database, until I start to move a table, drag and move a bit in a direction, then the whole page refreshes and all the lines are visible again. Please see image

![image](https://cloud.githubusercontent.com/assets/5622290/10920438/afde7812-8278-11e5-983f-521a4a842655.png)

**Comment by klmedia** [comment]
PS: or just click on a table makes the lines appear again. Thanks!

**Comment by ondras** [comment]
Can you please elaborate a bit more on how to reproduce this (buggy) behavior? I am having hard times getting it to show on the demo installation at http://ondras.zarovi.cz/sql/demo/?keyword=default ...

**Comment by klmedia** [comment]
create two tables and move one outside the grid area. make some key-forighn key links and save it. After you close the app, repoen and load the saved design, the link lines wouldn't be visible outside the grid area. At least this is happening to me. After I make a click on a table, all the lines appear normal. Thanks for your time!

**Comment by ondras** [comment]
Shall be fixed now.

**Comment by klmedia** [comment]
You got it!
Thanks Ondras! This is a very nice project :-)
