### ISSUE TITLE
Feature: AutoIncrement

### ISSUE THREAD

**Issue by VisualBean** [ondras/wwwsqldesigner#218]
I can't seem to find a checkbox for autoincrementation, I do believe this is supported, in all of the formats supported so far.

Would be nice :)

**Comment by ondras** [comment]
There is one -- just inbetween the "Default" and "NULL" fields. Please post a screenshot if you fail to locate it.

**Comment by VisualBean** [comment]
Inbetween those are the Primary Key field. As far as i know primary key doesnt have to be incremental? (I only work in mssql though)

**Comment by ondras** [comment]
Sounds like a localization issue then? Can you switch to English and post a screenshot?

**Comment by VisualBean** [comment]
![dbdesigner](https://cloud.githubusercontent.com/assets/5294032/12765269/33a6f8f0-c9fe-11e5-92f2-aa55bc88b892.png)

Here you go - Im using FireFox 43.0.4

**Comment by ondras** [comment]
@VisualBean, you are apparently using some un-official version of the wwwsqldesigner (judging from the screenshot). The official version looks like this: http://ondras.zarovi.cz/sql/demo/?keyword=default
