### ISSUE TITLE
Postgres Export XML instructions

### ISSUE THREAD

**Issue by morenoh149** [ondras/wwwsqldesigner#226]
How can I get an xml file that will load into wwwsqldesigner? I'm able to export xml from my database doing
```
select schema_to_xmlschema('public', true, true, 'example-ns');
```

but I don't think this format is compatible with this tool. Thoughts?

**Comment by ondras** [comment]
WWWSQLDesigner uses its own XML format, right. Some backends, such as the [php-mysql](https://github.com/ondras/wwwsqldesigner/blob/master/backend/php-mysql/index.php#L39), implement importing from DB to this XML.

**Comment by morenoh149** [comment]
doesn't seem trivial
