### ISSUE TITLE
Cannot add more than 6 tables

### ISSUE THREAD

**Issue by trevorpan** [ondras/wwwsqldesigner#260]
Hi Ondras, 

Not sure what may be causing this. When I click add table nothing happens in chrome. Has this issue occurred for you?

Best regards,

Trevor

[Illustrata.txt](https://github.com/ondras/wwwsqldesigner/files/1456170/Illustrata.txt)

**Comment by ondras** [comment]
Hi @trevorpan,

I have not experienced this behavior. Can you open the DevTools Console (typically by pressing the F12 key) and check whether there are some JS exceptions reported?

**Comment by trevorpan** [comment]
Sorry, I did not get back with you. Was finishing up a semester and could not reproduce the issue. May have been school browsers, network? Anyhow, thank you for responding. It's a great tool you made.

**Comment by CyrilCharlier** [comment]
Hi @trevorpan 

So you can close this issue i think :)

thanks,
