### ISSUE TITLE
Reverse Enginering support For Postgres?

### ISSUE THREAD

**Issue by martinmurciego** [ondras/wwwsqldesigner#272]
Good tool. I am interested in the function of drawing the diagram doing inverse engineering of a sql script (DDL) of a postgres database.

**Comment by ondras** [comment]
I would love to see the feature as well. Alas, my PSQL knowledge is rather limited and implementing the necessary `import` server-side call requires a skilled/experienced PSQL developer.

If you are a postgres guy, you might want to have a look at https://github.com/ondras/wwwsqldesigner/blob/master/backend/php-postgresql/index.php -- there already **is** some code for importing schema from Postgres, but I have no idea whether that works or not.

**Comment by martinmurciego** [comment]
I would like to collaborate on a tool like this although I only have some knowledge / experience in: PSQL (Postgres), Javacript and Node js. And none in PHP I can only comprehend roughly the code that I read, but not modify it and set it up.

**Comment by ondras** [comment]
And the existing php-postgresql backend is not working for you? Does it import any data?

**Comment by martinmurciego** [comment]
I can only tell you that the queries used are working perfectly for version 9.5 of postgres that I am using. It works to recover names of: tables, columns, PK, FK. It would be necessary to create a correspondence between Postgres data types and MySQL data types as some tools that normally distinguish a logical model from a physical model do to separate the definitions of those data types in the database engines. I would fail to try this code to see how to run it but the queries have access to the schema or catalog of the database.

**Comment by ondras** [comment]
Well, I am puzzled now. If the existing code works, what is this Issue / Feature request about? I thought that the current implementation for schema import is flawed in some way...

**Comment by martinmurciego** [comment]
The script may work or at least the queries may be working.

Well maybe the issue would be that this tool could incorporate uploading an sql / ddl script and that can generate the diagram. Because it is a tool that requires the user's machine to be installed in order to connect to the postgres / mysql database engine that the user must have previously installed. Now I understand that I must install this tool having a MySQL / Postgres installation and configure a connection to my database so that I can generate the schema.
I do not concentrate entirely on the fact that it is a PHP application that must be mounted on my computer to take advantage of the feature.
Well it's not bad, maybe it would be necessary to dedicate some time to do it offline with javascript code and make it allow to upload an SQL script instead of connecting to the database. When I make a place in my time I will contribute something surely.
