### ISSUE TITLE
How do i save the generated .sql script?

### ISSUE THREAD

**Issue by ganeshkbhat** [ondras/wwwsqldesigner#290]
How do i save the generated .sql script? I have followed the steps and unable to save. How do i do it? May be i am missing something

**Comment by ondras** [comment]
> How do i save the generated .sql script? I have followed the steps and unable to save. How do i do it? May be i am missing something

You use the clipboard to copy/paste it into a file of your choice :-)

**Comment by ganeshkbhat** [comment]
What are the PHP files in the Backend folder for?

**Comment by ondras** [comment]
> What are the PHP files in the Backend folder for?

For server-side saving, loading and importing.



>  I haven't been able to figure out the save and load button in the www designer :-) I am sure the Backend works but seems like there are too many dependencies put separately

You need to have a working server-side setup for this -- a webserver, a PHP installation and a database.
