### ISSUE TITLE
Error 500 when save to PostGreSql

### ISSUE THREAD

**Issue by msvp** [ondras/wwwsqldesigner#302]
Hello  from France !

I've got an Error 500 when I save my Work to a PostGreSQL DataBase.

This is my Table Configuration : https://msieursvp.fr/nextcloud/s/osLiii4XYzEwkAn

I've created a wwwsqldesigner Database, with the role wwwsqldesigner (password = "xxx").

What is Wrong in my config ?
Any Idea ?

Many Thanks !

**Comment by mhenselin** [comment]
Do you have any more information about the error? Just the 500 code does unfortunately not give enough information.

**Comment by msvp** [comment]
No error in the Nginx Log, no error in the Postgres Log.

When I click on the save button, this is the log error from Google Chrome : 
oz.js:222 POST https://msieursvp.fr/sqldesigner/backend/php-postgresql/?action=save&keyword=Test3 500 (Internal Server Error)
Request @ oz.js:222
SQL.IO.serversave @ wwwsqldesigner.js:1463

**Comment by msvp** [comment]
I've found why !
In fact, i had to modify the Host_addr in /backend/php_postgresql/index.php to fit my config.
Many thanks !

P.S. : To had to the installation intructions in case the postgres server was not in the localhost...
