### ISSUE TITLE
[SECURITY] POSTing without token

### ISSUE THREAD

**Issue by bilogic** [ondras/wwwsqldesigner#311]
Hi,

It is not safe for javascript to POST without a CSRF/bearer token, the scripts should accomodate for it. Thank you.

**Comment by ondras** [comment]
As far as I can tell, the only JS-initiated POST request is equipped with with a [non-form Content-type header](https://github.com/ondras/wwwsqldesigner/blob/68df5aca2d6669cab052d2a6f06080b84737a34b/js/io.js#L412), so a CSRF is prevented via a CORS Preflight.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests for reference.

**Comment by bilogic** [comment]
Hmm, what I'm trying to point out is that, POSTs can be sent and have an effect without having to load the editor UI first (to get the token). 

Of course in the strict sense, the main focus of this library is to demonstrate the editor's capabilities, thus the token can be left to the developer. However, incorporating a token requires modifying the JS files, which creates a fork, not that good for developer experience if we are just looking to utliize this library.

I have coded up the authorization bearer tokens, but it is based on https://github.com/Lt-Mayonesa/wwwsqldesigner. Perhaps another approach is to allow specifying extra XHR headers when instantiating `var d = new SQL.Designer();`, this way, the token can be passed in and no modification of the JS files is needed.

Hope I'm making sense. Thank you.

**Comment by ondras** [comment]
> Hmm, what I'm trying to point out is that, POSTs can be sent and have an effect without having to load the editor UI first (to get the token).

I see. The issue is not related to the JS app, but rather to the php-mysql backend implementation.

However, the currently provided backend does not perform any kind of authorization (it is literally open to anything), so I see little sense in performing a token validation in this case. Any attacker is free to POST any data to the backend - either via the app itself, or via custom HTTP requests.

**Comment by bilogic** [comment]
> I see. The issue is not related to the JS app, but rather to the php-mysql backend implementation.

Yes, I recognize that now. However, the backend alone cannot mitigate the attacks, it requires the JS to "play" its part too.

I can see a clear solution now, there is no need to validate any token, just allow specifying additional XHR headers during instantiation, this way, developers who need the authorization/security won't have to modify the JS files.

If you are open to this, I could file a PR. Thank you.
